# This is a development docker-compose.yml, don't use this one in production
version: "3.4"

x-baricadr-variables: &baricadr-variables
    BARICADR_RUN_MODE: "dev"
    BARICADR_REPOS_CONF: "test-data/sample_repos.yml"
    TZ: "Etc/UTC"


services:
    baricadr:
        build: ./
        ports:
            - 9100:80
        depends_on:
            - redis
            - db
        environment: *baricadr-variables
        volumes:
            - ./test-data/test-fs-mountpoint/:/repos/
            - ./:/baricadr/
            - ./docker/uwsgi_dev.ini:/etc/uwsgi/uwsgi.ini:ro

    worker:
        build:
            context: .
            dockerfile: docker_celery/Dockerfile
        depends_on:
            - redis
            - db
        entrypoint: python3
        command: /opt/celery_dev_launch.py
        environment: *baricadr-variables
        volumes:
            - ./test-data/test-fs-mountpoint/:/repos/
            - ./:/baricadr/:ro
            - ./docker_celery/celery_dev_launch.py:/opt/celery_dev_launch.py:ro

    monitor:
        build:
            context: .
            dockerfile: docker_celery/Dockerfile
        ports:
            - "5555:5555"
        entrypoint: celery
        command: flower -A baricadr.tasks.celery --port=5555 --loglevel=info --autoreload
        depends_on:
            - redis
        environment: *baricadr-variables
        volumes:
            - ./:/baricadr/:ro

    redis:
        image: redis:4.0

    mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
            - "1025:1025"
            - "8025:8025"

    sftp:
        image: atmoz/sftp
        command: foo:pass:1001
        volumes:
            - ./test-data/test-repo/:/home/foo/test-repo/:ro
            - ./test-data/test-repo-sftp/:/home/foo/test-repo-sftp/:ro

    db:
        image: postgres:11-alpine
        environment:
          POSTGRES_PASSWORD: postgres
